
name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn semantic-release


      